core/urls.py
from django.urls import path 

from .import views

app_name = 'core'

urlpatterns = [
    path('todo/', views.display_tasks, name='todo'),
    path('task_list/', views.task_list, name='task_list'),
    path('check/', views.check, name='check'),

    path('lodolist/', views.TodoList.as_view(), name='todolist'),
    path('addtodo/', views.add_todo, name='addtodo'),
    path('delete_todo/<int:pk>/', views.delete_todo, name='delete_todo'),
    path('undo_todo/<int:pk>/', views.undo_todo, name='undo_todo'),
    path('complete_todo/<int:pk>/', views.complete_todo, name='complete_todo'),
    path('edit_todo/<int:pk>/edit/', views.edit_todo, name='edit_todo'),
    path('after_edit/', views.after_edit, name='after_edit'),

    path('task/', views.get_task, name='task'),

]

htmx/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('core/', include('core.urls', namespace='core')),
]

core/models.py
from django.db import models

class Todo(models.Model):
    name = models.CharField(max_length=200)
    create_date = models.DateTimeField(auto_now_add=True)
    dute_date = models.DateTimeField(blank=True, null=True)
    completed = models.BooleanField(default=False)


    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ["-name"]
        verbose_name_plural='1. Todo'

core/forms.py
from django import forms
from django.forms import ModelForm
from .models import Todo


class TaskForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ("name",)
        # labels = {
        #     "name": "Add new task:",
        # }

core/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic
from django.http import HttpResponse
from .models import Todo
from .forms import TaskForm


def task_list(request):
    todo = Todo.objects.all()

    return render(request, 'task_list.html', {'todo':todo})

def display_tasks(request):
    form = TaskForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            task = form.save(commit=False)
            t = request.POST.get("name")
            if Todo.objects.filter(name=t).exists():
                print('not adding anything you type')
            else:

                # task.user = request.user
                task.save()
    todo = Todo.objects.all()
    return render(request, 'todo.html', {'todo': todo, 'form':form})


def check(request):
    taskname = request.POST.get("name")

    if Todo.objects.filter(name=taskname):
        return HttpResponse("<div style='color:red'>This task already exist <div>")
    else:
        return HttpResponse("<div style='color:green'>This task not exist <div>")


class TodoList(generic.ListView):
    model = Todo
    template_name = "todolist.html"
    context_object_name = 'todo'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['info'] = Todo.objects.all()
        return context

def add_todo(request):
    form = TaskForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            task = form.save(commit=False)
            name = request.POST.get("name")
            if Todo.objects.filter(name=name).exists():
                print('not adding anything you type')
            else:
                # task.user = request.user
                task.save()
    todo = Todo.objects.all()
    return render(request, 'todo.html', {'todo': todo, 'form':form})

def delete_todo(request, pk):
    dele = Todo.objects.filter(id=pk).delete()
    todo = Todo.objects.all()
    return render(request, 'todo.html', {'todo':todo})

def complete_todo(request, pk):
    dele = Todo.objects.filter(id=pk)
    print(dele.values(), 'printing current value')
    for i in dele:
        i.completed = True
        i.save()
   
    todo = Todo.objects.all()
    return render(request, 'todo.html', {'todo':todo})

def undo_todo(request, pk):
    dele = Todo.objects.filter(id=pk)
    print(dele.values(), 'printing current value')
    for i in dele:
        i.completed = False
        i.save()
    todo = Todo.objects.all()
    return render(request, 'todo.html', {'todo':todo})

def edit_todo(request, pk):
    todo = Todo.objects.all()
    question = Todo.objects.get(id=pk)
    form = TaskForm(request.POST, instance=question)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('core:after_edit')
    return render(request, 'edit.html', {'todo':question, 'form':form})

def after_edit(request):
    todo = Todo.objects.filter()
    return render(request, 'edit_back.html', {'todo':todo})
    

def get_task(request):
    task = Todo.objects.all()
    return render(request, 'htmx.html', {'todo': task})
 

core/templates/edit.html
<form hx-post="{% url 'core:edit_todo' todo.pk %}" hx-target="#edit">
    {% csrf_token %}
    <input type="text" name="name" maxlength="200" required="" id="id_name" value="{{todo.name}}">
    <button type="submit" hx-target="edit" class="btn btn-dark" >save</button>
</form>

<div>
    
</div>
  

core/templates/edit_back.html
{% load static %}
           <!-- Demo header-->
           <section class="pb-5 header text-center">
            <div class="row">    
                            <!-- Responsive table -->
                            <div class="table-responsive">
                                <table class="table m-0">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Updated Task</th>
                                            <!-- <th scope="col">Last</th> -->
                                            <th scope="col"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
        
        
                                        {% for todo in todo  %}
        
                                        {% if todo.completed == False %}

                                        <div id="edit">

                                        </div>
                                    

                                        <tr>
                                            <th scope="row"> {{ forloop.counter }} </th>
                                            <td id="edit">{{todo.name}}</td>
                                          <!--   <td>@mdo</td> -->
                                            <td>
                                                <!-- Call to action buttons -->
                                                <ul class="list-inline m-0">
                                                    <li class="list-inline-item"> 
                                                        <button hx-post="{% url 'core:complete_todo' todo.pk %}" hx-target="#todolist"
                                                        class="btn btn-primary btn-sm rounded-0" 
                                                        type="button" data-toggle="tooltip"
                                                         data-placement="top" title="Add"><i class="fa fa-check"></i></button>
                                                    </li>
                                                    <li class="list-inline-item">    
                                                        <button hx-get="{% url 'core:edit_todo' todo.pk %}" hx-target="#edit" 
                                                        class="btn btn-success btn-sm rounded-0" type="button" data-toggle="tooltip" data-placement="top" title="Edit">
                                                            <i class="fa fa-edit"></i></button>
                                                    </li>
                                                    <li class="list-inline-item">
                                                        <button hx-delete="{% url 'core:delete_todo' todo.pk %}" hx-target="#todolist"
                                                        hx-confirm="Are you sure?" class="btn btn-danger btn-sm rounded-0" type="button" data-toggle="tooltip"
                                                         data-placement="top" title="Delete"><i class="fa fa-trash"></i></button>
                                                    </li>
                                                </ul>
                                            </td>
                                        </tr> 
                                         {% endif %}
                                        
                                        {% endfor %}
                                    </tbody>  
                               
                             </table>
                    </div>
            </div>
            
        </section>
        
             

core/templates/htmx.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        {% for i in todo  %}

     
            <b>
                <i style="color: salmon;">{{i.name}}</i> <br>
            </b>
     
          
        {% endfor %}
    </div>
</body>
</html>

core/templates/hx_base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <script src="https://unpkg.com/htmx.org@1.6.0"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://use.fontawesome.com/6db9d51ae7.js"></script>
    <style>
@import url("https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;700&family=Lato:ital,wght@0,300;0,400;1,300;1,400&display=swap");

* {
  margin: 0;
  padding: 0;
  outline: 0;
  box-sizing: border-box;
  -webkit-font-smoothing: antialiased;
  user-select: none;
}


a {
  text-decoration: none;
  color: inherit;
}


#app {
  width: 50%;
  min-width: 400px;
}

h1 {
  font-family: "Dancing Script", cursive;
  text-align: center;
  margin-bottom: 50px;
  font-size: 45px;
  color: #335c62;
  font-weight: 700;
}

p {
  font-family: "Dancing Script", cursive;
  text-align: center;
  margin-top: 30px;
  font-size: 30px;
  color: #5c5c5c;
  font-weight: 300;
}



ul li {
  margin-bottom: 10px;
  color: #5c5c5c;
}



ul li a:hover {
  opacity: 0.8;
}

input,
button {
  font: 400 20px "Lato", sans-serif;
}

input {
  width: 60%;
  height: 40px;
  color: #5c5c5c;
  border: 1px solid #dcdce6;
  border-radius: 8px;
  padding: 0 24px;
  margin-right: 10px;
}

.btn_add {
  width: 30%;
  height: 40px;
  border: 1px solid #dcdce6;
  border-radius: 8px;
  background-color: #59a2ad;
  color: #fff;
  cursor: pointer;
}

.btn_add:hover {
  opacity: 0.9;
}

        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
      </style>
  
      
      <!-- Custom styles for this template -->
      <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
      <!-- Custom styles for this template -->
      <link href="blog.css" rel="stylesheet">
    </head>
    <body>
      
  <div class="container">
    <header class="blog-header py-3">
      <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
          <a class="link-secondary" href="#">Subscribe</a>
        </div>
        <div class="col-4 text-center">
          <a class="blog-header-logo text-dark" href="#">Large</a>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
          <a class="link-secondary" href="#" aria-label="Search">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
          </a>
          <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
        </div>
      </div>
    </header>
  
    <div class="nav-scroller py-1 mb-2">
      <nav class="nav d-flex justify-content-between">
        <a class="p-2 link-secondary" href="#">World</a>
        
      </nav>
    </div>
  </div>
  
  {% block content %}
    
  {% endblock content %}
  

    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
          event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
      </script>
  </body>
</html>

core/templates/todo.html
           <!-- Demo header-->
<section class="pb-5 header text-center">
    <div class="row">    
                    <!-- Responsive table -->
                    <div class="table-responsive">
                        <table class="table m-0">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Task Name</th>
                                    <!-- <th scope="col">Last</th> -->
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>


                                {% for todo in todo  %}

                                {% if todo.completed == False %}

                                
                                <tr>
                                    <th scope="row"> {{ forloop.counter }} </th>
                                    <td>{{todo.name}}</td>
                                 <id id="edit"></id>
                                    
                                  <!--   <td>@mdo</td> -->
                                    <td>
                                        <!-- Call to action buttons -->
                                        <ul class="list-inline m-0">
                                            <li class="list-inline-item"> 
                                                <button hx-post="{% url 'core:complete_todo' todo.pk %}" hx-target="#todolist"
                                                class="btn btn-primary btn-sm rounded-0" 
                                                type="button" data-toggle="tooltip"
                                                 data-placement="top" title="Add"><i class="fa fa-check"></i></button>
                                            </li>
                                            <li class="list-inline-item">    
                                                <button hx-get="{% url 'core:edit_todo' todo.pk %}" hx-target="#edit" 
                                                class="btn btn-success btn-sm rounded-0" type="button" data-toggle="tooltip" data-placement="top" title="Edit">
                                                    <i class="fa fa-edit"></i></button>
                                            </li>
                                            <li class="list-inline-item">
                                                <button hx-delete="{% url 'core:delete_todo' todo.pk %}" hx-target="#todolist"
                                                hx-confirm="Are you sure?" class="btn btn-danger btn-sm rounded-0" type="button" data-toggle="tooltip"
                                                 data-placement="top" title="Delete"><i class="fa fa-trash"></i></button>
                                            </li>
                                        </ul>
                                    </td>
                                </tr> 
                                 {% endif %}
                                
                                {% endfor %}
                            </tbody>  
                       
                     </table>
            </div>
    </div>
</section>

           <!-- Demo header-->
           <section class="pb-5 header text-center">
            <div class="row">    
                            <!-- Responsive table -->
                            <div class="table-responsive">
                                <table class="table m-0">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Completed Task</th>
                                            <!-- <th scope="col">Last</th> -->
                                            <th scope="col"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for todo in todo  %}
        
                                        {% if todo.completed == True %}
                                          
                                        <tr>
                                            <th scope="row"> {{ forloop.counter }} </th>
                                            <td style="text-decoration: line-through;">{{todo.name}}</td>
                                            <!-- <td>{{todo.completed}}</td> -->
                                          <!--   <td>@mdo</td> -->
                                            <td>
                                                <!-- Call to action buttons -->
                                                <ul class="list-inline m-0">
                                                    <li class="list-inline-item">
                                                        <button hx-post="{% url 'core:undo_todo' todo.pk %}" hx-target="#todolist" class="btn btn-primary btn-sm rounded-0" type="button" data-toggle="tooltip"
                                                         data-placement="top" title="Add"><i class="fa fa-undo"></i></button>
                                                    </li>
                                                 <!--    <li class="list-inline-item">
                                                        <button class="btn btn-success btn-sm rounded-0" type="button" data-toggle="tooltip" data-placement="top" title="Edit"><i class="fa fa-edit"></i></button>
                                                    </li> -->
                                                    <li class="list-inline-item">
                                                        <button hx-delete="{% url 'core:delete_todo' todo.pk %}" hx-target="#todolist"
                                                        hx-confirm="Are you sure?" class="btn btn-danger btn-sm rounded-0" type="button" data-toggle="tooltip"
                                                         data-placement="top" title="Delete"><i class="fa fa-trash"></i></button>
                                                    </li>
                                                </ul>
                                            </td>
                                        </tr> 
                                         {% endif %}
                                        
                                        {% endfor %}
                                    </tbody>  
                               
                             </table>
                    </div>
            </div>
        </section>

core/templates/todolist.html
{% extends "hx_base.html" %}
{% load static %}

{% block content %}

<main class="container">
      
  
    <div class="row g-5">
      <div class="col-md-8">
     

        <div id="app">
            <h1>to do list</h1> 
            <form>
                {% csrf_token %} 
              
           <input type="text" name="name" maxlength="200"
           required="" id="id_name" placeholder="New task" hx-post="{% url 'core:check' %}" hx-swap="outerhtml" hx-trigger="keyup" 
           hx-target="#checktask">


            <button class='btn_add' type="submit" hx-post="{% url 'core:addtodo' %}" 
            hx-target='#todolist'>Add</button>

                    <div id='checktask'>
                    </div>
           </form> 
            <div id="todolist">
               
            {% include "todo.html" %}

            </div>



        </div>

      </div>

    </div>
  
  </main>
  
{% endblock content %}